fail_fast: false
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.8
    hooks:
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: pretty-format-json
        name: json
        args: [--autofix, --indent=4, --no-ensure-ascii]
        exclude: .cruft.json
      - id: check-yaml
        name: yaml
        exclude: templates\/[a-z_-]+.yaml
      - id: end-of-file-fixer
        name: eof
      - id: trailing-whitespace
        name: whitespaces
      - id: fix-byte-order-marker
        name: byte-order
