"""
InvenioRDM settings for mex-invenio project.

This file was automatically generated by 'invenio-cli init'.

For the full list of settings and their values, see
https://inveniordm.docs.cern.ch/reference/configuration/.
"""
import os
# Standard library imports
from datetime import datetime

# Third-party imports
import invenio_rdm_records.services.config as rdm_config
from invenio_app_rdm.config import OAISERVER_METADATA_FORMATS
from invenio_i18n import lazy_gettext as _
from invenio_oauthclient.views.client import auto_redirect_login
from invenio_rdm_records.config import RDM_SEARCH, RDM_FACETS
from invenio_vocabularies.services.facets import VocabularyLabels

# Local imports
from mex_invenio.custom_facets import RestrictedTermsFacet
from mex_invenio.custom_fields import field_types
from mex_invenio.custom_fields.custom_fields import (
    RDM_NAMESPACES,
    RDM_CUSTOM_FIELDS,
    RDM_CUSTOM_FIELDS_UI,
)
from mex_invenio.custom_fields.field_types import get_field_types
from mex_invenio.custom_fields.pref_labels import get_pref_labels
from mex_invenio.custom_fields.ext_ids import get_ext_ids
from mex_invenio.custom_fields.backwards_linked_records import (
    get_fields_linked_backwards,
)

from mex_invenio.records.api import MexRDMRecord, MEXBulkIndexer
from mex_invenio.services.schema import MexRDMRecordSchema


def _(x):  # needed to avoid start time failure with lazy strings
    return x


# Flask
# =====
# See https://flask.palletsprojects.com/en/1.1.x/config/

# Define the value of the cache control header `max-age` returned by the server when serving
# public files. Files will be cached by the browser for the provided number of seconds.
# See flask documentation for more information:
# https://flask.palletsprojects.com/en/2.1.x/config/#SEND_FILE_MAX_AGE_DEFAULT
SEND_FILE_MAX_AGE_DEFAULT = 300

# SECURITY WARNING: keep the secret key used in production secret!
# Do not commit it to a source code repository.
# TODO: Set
SECRET_KEY = "CHANGE_ME"

# Since HAProxy and Nginx route all requests no matter the host header
# provided, the allowed hosts variable is set to localhost. In production it
# should be set to the correct host and it is strongly recommended to only
# route correct hosts to the application.
APP_ALLOWED_HOSTS = ["0.0.0.0", "localhost", "127.0.0.1"]

# Flask-SQLAlchemy
# ================
# See https://flask-sqlalchemy.palletsprojects.com/en/2.x/config/

# TODO: Set
SQLALCHEMY_DATABASE_URI = (
    "postgresql+psycopg2://mex-invenio:mex-invenio@localhost/mex-invenio"
)

# Invenio-App
# ===========
# See https://invenio-app.readthedocs.io/en/latest/configuration.html

APP_DEFAULT_SECURE_HEADERS = {
    "content_security_policy": {
        "default-src": [
            "'self'",
            "data:",  # for fonts
            "'unsafe-inline'",  # for inline scripts and styles
            "blob:",  # for pdf preview
            # Add your own policies here (e.g. analytics)
        ],
    },
    "content_security_policy_report_only": False,
    "content_security_policy_report_uri": None,
    "force_file_save": False,
    "force_https": True,
    "force_https_permanent": False,
    "frame_options": "sameorigin",
    "frame_options_allow_from": None,
    "session_cookie_http_only": True,
    "session_cookie_secure": True,
    "strict_transport_security": True,
    "strict_transport_security_include_subdomains": True,
    "strict_transport_security_max_age": 31556926,  # One year in seconds
    "strict_transport_security_preload": False,
}

# Custom RDM Record Class which implements the additional features required
# by the Mex model (especially record indexing)
RDM_RECORD_CLS = MexRDMRecord
rdm_config.RDMRecordServiceConfig.schema = MexRDMRecordSchema
rdm_config.RDMRecordServiceConfig.record_cls = MexRDMRecord
rdm_config.RDMRecordServiceConfig.indexer_cls = MEXBulkIndexer

# Flask-Babel
# ===========
# See https://python-babel.github.io/flask-babel/#configuration

# Default locale (language)
# Default time zone
BABEL_DEFAULT_TIMEZONE = "Europe/Zurich"

# Invenio-I18N
# ============
# See https://invenio-i18n.readthedocs.io/en/latest/configuration.html

# Other supported languages (do not include BABEL_DEFAULT_LOCALE in list).
BABEL_DEFAULT_LOCALE = "de"
I18N_LANGUAGES = [("en", _("English"))]

# Invenio-Theme
# =============
# See https://invenio-theme.readthedocs.io/en/latest/configuration.html

# Name used in header and UI
THEME_SITENAME = "MEx"
# Frontpage title
THEME_FRONTPAGE_TITLE = "Metadata Exchange"
# Intro section
THEME_SHOW_FRONTPAGE_INTRO_SECTION = False
# Header logo
ORGANISATION_LOGO = "images/RKI-logo.svg"
THEME_LOGO = "images/mex-logo.svg"

# Invenio-App-RDM
# ===============
# See https://github.com/inveniosoftware/invenio-app-rdm/blob/master/invenio_app_rdm/config.py

# Instance's theme entrypoint file. Path relative to the ``assets/`` folder.
INSTANCE_THEME_FILE = "./less/theme.less"

# Email address for administrator emails (like file checksum alerts)
APP_RDM_ADMIN_EMAIL_RECIPIENT = "mex@rki.de"

# Default values for the deposit form
APP_RDM_DEPOSIT_FORM_DEFAULTS = {
    "publication_date": lambda: datetime.now().strftime("%Y-%m-%d"),
    "rights": [
        {
            "id": "cc-by-4.0",
            "title": "Creative Commons Attribution 4.0 International",
            "description": (
                "The Creative Commons Attribution license allows "
                "re-distribution and re-use of a licensed work "
                "on the condition that the creator is "
                "appropriately credited."
            ),
            "link": "https://creativecommons.org/licenses/by/4.0/legalcode",
        }
    ],
    "publisher": "mex-invenio",
}

APP_RDM_DEPOSIT_FORM_AUTOCOMPLETE_NAMES = "search"  # "search_only" or "off"

# Invenio-Records-Resources
# =========================
# See https://github.com/inveniosoftware/invenio-records-resources/blob/master/invenio_records_resources/config.py

# TODO: Set with your own hostname when deploying to production
SITE_UI_URL = "https://127.0.0.1"

SITE_API_URL = "https://127.0.0.1/api"

# Invenio-RDM-Records
# ===================
# See https://inveniordm.docs.cern.ch/customize/dois/
DATACITE_ENABLED = False
DATACITE_USERNAME = ""
DATACITE_PASSWORD = ""
DATACITE_PREFIX = ""
DATACITE_TEST_MODE = True
DATACITE_DATACENTER_SYMBOL = ""

# Authentication - Invenio-Accounts and Invenio-OAuthclient
# =========================================================
# See: https://inveniordm.docs.cern.ch/customize/authentication/

# Invenio-Accounts
# ----------------
# See https://github.com/inveniosoftware/invenio-accounts/blob/master/invenio_accounts/config.py
ACCOUNTS_LOCAL_LOGIN_ENABLED = True  # enable local login
SECURITY_REGISTERABLE = True  # local login: allow users to register
SECURITY_RECOVERABLE = True  # local login: allow users to reset the password
SECURITY_CHANGEABLE = True  # local login: allow users to change psw
SECURITY_CONFIRMABLE = True  # local login: users can confirm e-mail address
SECURITY_LOGIN_WITHOUT_CONFIRMATION = (
    False  # require users to confirm email before being able to login
)

# Invenio-OAuthclient
# -------------------
# See https://github.com/inveniosoftware/invenio-oauthclient/blob/master/invenio_oauthclient/config.py

OAUTHCLIENT_REMOTE_APPS = {}  # configure external login providers

ACCOUNTS_LOGIN_VIEW_FUNCTION = (
    auto_redirect_login  # autoredirect to external login if enabled
)
OAUTHCLIENT_AUTO_REDIRECT_TO_EXTERNAL_LOGIN = False  # autoredirect to external login

# Invenio-UserProfiles
# --------------------
USERPROFILES_READ_ONLY = (
    False  # allow users to change profile info (name, email, etc...)
)

# OAI-PMH
# =======
# See https://github.com/inveniosoftware/invenio-oaiserver/blob/master/invenio_oaiserver/config.py

OAISERVER_ID_PREFIX = "mex.rki.de"
"""The prefix that will be applied to the generated OAI-PMH ids."""
OAISERVER_ADMIN_EMAILS = [
    "mex@rki.de",
]

# configure a custom OAI metadata format for MEx
OAISERVER_METADATA_FORMATS["oai_dc"] = {
    "serializer": "mex_invenio.oai.mex:mex_dublincore_etree",
    "schema": "http://www.openarchives.org/OAI/2.0/oai_dc.xsd",
    "namespace": "http://www.openarchives.org/OAI/2.0/oai_dc/",
}

# a list of custom fields that will be included in the OAI-PMH output as dc:source
OAISERVER_SOURCES = ["mex:containedBy", "mex:wasGeneratedBy", "mex:usedIn"]

# a list of custom fields that will be included in the OAI-PMH output as dc:relation
OAISERVER_RELATIONS = ["mex:distribution", "mex:isPartOf", "mex:belongsTo"]

# Invenio-Search
# --------------

SEARCH_INDEX_PREFIX = "mex-invenio-"

# Invenio-Users-Resources
# -----------------------

USERS_RESOURCES_ADMINISTRATION_ENABLED = True
"""Enable the user administration"""

# S3 config

S3_DOWNLOAD_FOLDER = os.environ.get("INVENIO_S3_DOWNLOAD_FOLDER", "s3_downloads")

COMMUNITIES_GROUPS_ENABLED = False

# The value for the Datacite creator property in imported records
RECORD_METADATA_CREATOR = {
    "person_or_org": {
        "name": "Robert Koch Institute",
        "type": "organizational",
    },
}

# MEx properties to use as record title
RECORD_METADATA_TITLE_PROPERTIES = [
    "title",
    "name",
    "fullName",
    "label",
    "officialName",
    "email",
    "familyName",
]

# The default value for the Datacite title property in imported records
# if it is not present in the MEx source record
RECORD_METADATA_DEFAULT_TITLE = "[Untitled]"

# ---
# Custom facets
# ---

RDM_FACETS = {
    **RDM_FACETS,
    "restricted_resource_type": {
        "facet": RestrictedTermsFacet(
            field="metadata.resource_type.props.type",
            subfield="metadata.resource_type.props.subtype",
            splitchar="::",
            # Field to filter on
            label=_("Resource types"),
            value_labels=VocabularyLabels("resourcetypes"),
            excluded_values=[
                "accessplatform",
                "concept",
                "consent",
                "contactpoint",
                "distribution",
                "organization",
                "organizationalunit",
                "person",
                "primarysource",
                "variablegroup",
            ],
        ),
        "ui": {"field": "resource_type.id"},
    },
}

RDM_SEARCH = {**RDM_SEARCH, "facets": ["restricted_resource_type"]}

# ---------- UI --------------

UI_SETTINGS = {
    "resource": {
        "label": "Data Source/Dataset",
        "special_fields": {
            "RESOURCE_TYPE_SPECIFIC": {"field": "mex:resourceTypeSpecific"},
            "RESOURCE_TYPE_GENERAL": {"field": "mex:resourceTypeGeneral"},
            "CREATED": {"field": "mex:created"},
            "ACCESS_RESTRICTION": {
                "field": "mex:accessRestriction",
                "color_map": {
                    "https://mex.rki.de/item/access-restriction-1": "#d2ebd3",
                    "https://mex.rki.de/item/access-restriction-2": "#fcd0cd",
                },
            },
            "ALT_TITLE": {"field": "mex:alternativeTitle"},
            "DESCRIPTION": {"field": "mex:description"},
            "LANGUAGE": {"field": "mex:language"},
            "MODIFIED": {"field": "mex:modified"},
            "MESH_ID": {
                "field": "mex:meshId",
                "prefixes": ["http://id.nlm.nih.gov/mesh/"],
            },
            "LOINC": {"field": "mex:loincId", "prefixes": ["https://loinc.org/"]},
            "ICD10": {"field": "mex:icd10code"},
            "TITLE": {"field": "mex:title"},
        },
        "main": {
            "creators": {
                "title": "Creators & Contributors",
                "icon": "creators.svg",
                "properties": [
                    {"field": "mex:creator", "label": "Author"},
                    {"field": "mex:unitInCharge", "label": "Responsible unit"},
                    {"field": "mex:contributor", "label": "Contributor"},
                    {"field": "mex:contributingUnit", "label": "Contributing unit"},
                    {"field": "mex:externalPartner", "label": "External partner"},
                ],
            },
            "theme": {
                "title": "Theme & Keywords",
                "icon": "theme.svg",
                "template": "theme_keywords.html",
                "properties": [
                    {"field": "mex:theme"},
                    {"field": "mex:keyword"},
                ],
            },
            "coverage": {
                "title": "Data Representation & Coverage",
                "icon": "coverage.svg",
                "properties": [
                    {"field": "mex:temporal", "label": "Temporal coverage"},
                    {"field": "mex:spatial", "label": "Spatial"},
                    {"field": "mex:minTypicalAge", "label": "Min. typical age"},
                    {"field": "mex:maxTypicalAge", "label": "Max. typical age"},
                    {"field": "mex:populationCoverage", "label": "Population coverage"},
                    {"field": "mex:sizeOfDataBasis", "label": "Size of data basis"},
                ],
            },
            "legal": {
                "title": "Legal Basis & Data Provenance",
                "icon": "legal.svg",
                "properties": [
                    {"field": "mex:hasLegalBasis", "label": "Legal basis"},
                    {"field": "mex:hasPurpose", "label": "Purpose of data processing"},
                    {"field": "mex:hasPersonalData", "label": "Personal data"},
                ],
            },
            "processing": {
                "title": "Data Collection & Processing",
                "icon": "processing.svg",
                "properties": [
                    {"field": "mex:resourceCreationMethod", "label": "Creation method"},
                    {"field": "mex:accrualPeriodicity", "label": "Update frequency"},
                    {
                        "field": "mex:anonymizationPseudonymization",
                        "label": "Anonymization/pseudonymization",
                    },
                    {"field": "mex:instrumentToolOrApparatus", "label": "Tool"},
                ],
            },
            "quality": {
                "title": "Standards & Quality",
                "icon": "quality.svg",
                "properties": [
                    {"field": "mex:conformsTo", "label": "Standard"},
                    {"field": "mex:qualityInformation", "label": "Quality information"},
                ],
            },
            "methodology": {
                "title": "Methodology",
                "icon": "methodology.svg",
                "properties": [
                    {"field": "mex:method", "label": "Method"},
                    {"field": "mex:methodDescription", "label": "Method description"},
                ],
            },
            "publication": {
                "title": "Related Publications & Further Documentation",
                "icon": "publication.svg",
                "properties": [
                    {
                        "field": "mex:publication",
                        "label": "Publication",
                        "is_backwards_linked": True,
                    },
                    {"field": "mex:documentation", "label": "Documentation"},
                ],
            },
            "generatedBy": {
                "title": "Related Projects",
                "icon": "relatedProjects.svg",
                "properties": [
                    {
                        "field": "mex:wasGeneratedBy",
                        "label": "Related project/endeavor",
                        "is_backwards_linked": True,
                    },
                ],
            },
            "relatedResources": {
                "type": "container",
                "title": "Related Resources",
                "icon": "relatedResources.svg",
                "components": [
                    {
                        "type": "component",
                        "title": "Part Of",
                        "properties": [
                            {"field": "mex:isPartOf"},
                        ],
                    },
                    {
                        "type": "component",
                        "title": "Includes",
                        "properties": [
                            {"field": "mex:isPartOf", "is_backwards_linked": True},
                        ],
                    },
                ],
            },
        },
        "side_bar": {
            "contact": {
                "title": "Contact",
                "template": "contact.html",
                "icon": "contact.svg",
                "properties": [
                    {"field": "mex:contact"},
                ],
            },
            "access": {
                "title": "Access & Usage Rights",
                "icon": "access.svg",
                "properties": [
                    {"field": "mex:accessRestriction", "label": "Access restriction"},
                    {
                        "field": "mex:doi",
                        "label": "Doi",
                        "prefixes": [
                            "https://dx.doi.org/",
                            "http://doi.org/",
                            "https://doi.org/",
                            "http://dx.doi.org/",
                        ],
                    },
                    {"field": "mex:license", "label": "License"},
                    {"field": "mex:rights", "label": "Rights"},
                ],
            },
            "files": {
                "title": "Files",
                "icon": "distribution.svg",
                "properties": [
                    {"field": "mex:distribution", "label": "Distribution"},
                ],
            },
            "variables": {
                "title": "Variables",
                "icon": "variables.svg",
                "properties": [
                    {"field": "mex:usedIn", "is_backwards_linked": True},
                ],
            },
        },
    },
    "activity": {
        "label": "Project",
        "special_fields": {
            "ALT_TITLE": {"field": "mex:alternativeTitle"},
            "ACTIVITY_TYPE": {"field": "mex:activityType"},
            "ABSTRACT": {"field": "mex:abstract"},
            "TITLE": {"field": "mex:title"},
        },
        "main": {
            "creators": {
                "title": "Creators & Contributors",
                "icon": "creators.svg",
                "properties": [
                    {"field": "mex:involvedPerson", "label": "Contributor"},
                    {"field": "mex:responsibleUnit", "label": "Responsible unit"},
                    {"field": "mex:involvedUnit", "label": "Contributing unit"},
                ],
            },
            "description": {
                "title": "Description",
                "icon": "description.svg",
                "properties": [
                    {"field": "mex:start", "label": "Start"},
                    {"field": "mex:end", "label": "End"},
                    {"field": "mex:theme", "label": "Theme"},
                ],
            },
            "partners": {
                "title": "Partners & Funding",
                "icon": "funding.svg",
                "properties": [
                    {"field": "mex:externalAssociate", "label": "External partner"},
                    {
                        "field": "mex:funderOrCommissioner",
                        "label": "Funded / commissioned by",
                    },
                    {"field": "mex:fundingProgram", "label": "Funding program"},
                ],
            },
            "publication": {
                "title": "Related Publications & Further Documentation",
                "icon": "publication.svg",
                "properties": [
                    {"field": "mex:publication", "label": "Publication"},
                    {"field": "mex:documentation", "label": "Documentation"},
                    {"field": "mex:website", "label": "Website"},
                ],
            },
            "parentResources": {
                "type": "container",
                "title": "Parent Resources",
                "icon": "relatedResources.svg",
                "components": [
                    {
                        "type": "component",
                        "title": "Part Of",
                        "properties": [
                            {"field": "mex:isPartOfActivity"},
                        ],
                    }
                ],
            },
            "relatedResources": {
                "type": "container",
                "title": "Related Resources",
                "icon": "relatedResources.svg",
                "components": [
                    {
                        "title": "Succeeds",
                        "properties": [
                            {"field": "mex:succeeds", "label": "Succeeds"},
                        ],
                    },
                    {
                        "title": "Generated By",
                        "properties": [
                            {
                                "field": "mex:wasGeneratedBy",
                                "label": "Related project/endeavor",
                                "is_backwards_linked": True,
                            },
                        ],
                    },
                ],
            },
        },
        "side_bar": {
            "contact": {
                "title": "Contact",
                "template": "contact.html",
                "icon": "contact.svg",
                "properties": [
                    {"field": "mex:contact"},
                ],
            }
        },
    },
    "bibliographicresource": {
        "label": "Publication",
        "special_fields": {
            "CREATED": {"field": "mex:created"},
            "ACCESS_RESTRICTION": {
                "field": "mex:accessRestriction",
                "color_map": {
                    "https://mex.rki.de/item/access-restriction-1": "#d2ebd3",
                    "https://mex.rki.de/item/access-restriction-2": "#fcd0cd",
                },
            },
            "ALT_TITLE": {"field": "mex:alternativeTitle"},
            "LANGUAGE": {"field": "mex:language"},
            "ABSTRACT": {"field": "mex:abstract"},
            "BIBLIOGRAPHICRESOURCE_TYPE": {"field": "mex:bibliographicResourceType"},
            "ISSUED": {"field": "mex:issued"},
            "TITLE": {"field": "mex:title"},
        },
        "main": {
            "creators": {
                "title": "Creators",
                "icon": "creators.svg",
                "properties": [
                    {"field": "mex:creator", "label": "Author"},
                    {"field": "mex:contributingUnit", "label": "Contributing unit"},
                ],
            },
            "keywords": {
                "title": "Keywords",
                "icon": "theme.svg",
                "properties": [
                    {"field": "mex:keyword"},
                ],
            },
            "titleProper": {
                "title": "Title Proper",
                "icon": "titleProper.svg",
                "properties": [
                    {"field": "mex:journal", "label": "Journal"},
                    {"field": "mex:issue", "label": "Issue"},
                    {"field": "mex:volume", "label": "Volume"},
                    {"field": "mex:titleOfBook", "label": "Book title"},
                    {"field": "mex:subtitle", "label": "Subtitle"},
                    {"field": "mex:titleOfSeries", "label": "Title of series"},
                    {"field": "mex:volumeOfSeries", "label": "Volume of series"},
                    {"field": "mex:section", "label": "Section"},
                ],
            },
            "imprint": {
                "title": "Imprint",
                "icon": "imprint.svg",
                "properties": [
                    {"field": "mex:publisher", "label": "Publisher"},
                    {"field": "mex:publicationPlace", "label": "Publication place"},
                    {"field": "mex:publicationYear", "label": "Publication year"},
                    {"field": "mex:pages", "label": "Pages"},
                    {"field": "mex:isbnissn", "label": "ISBN / ISSN"},
                ],
            },
            "editor": {
                "title": "Editor",
                "icon": "editor.svg",
                "properties": [
                    {"field": "mex:editor", "label": "Editor"},
                    {"field": "mex:editorOfSeries", "label": "Editor of the series"},
                ],
            },
            "relatedResources": {
                "type": "container",
                "title": "Related Resources",
                "icon": "relatedResources.svg",
                "components": [
                    {
                        "type": "component",
                        "properties": [
                            {
                                "field": "mex:publication",
                                "label": "Publication",
                                "is_backwards_linked": True,
                            },
                        ],
                    }
                ],
            },
        },
        "side_bar": {
            "access": {
                "title": "Access & Usage Rights",
                "icon": "access.svg",
                "properties": [
                    {"field": "mex:accessRestriction", "label": "Access restriction"},
                    {
                        "field": "mex:doi",
                        "label": "Doi",
                        "prefixes": [
                            "https://dx.doi.org/",
                            "http://doi.org/",
                            "https://doi.org/",
                            "http://dx.doi.org/",
                        ],
                    },
                    {"field": "mex:alternateIdentifier", "label": "Other identifier"},
                    {"field": "mex:repositoryURL", "label": "Repository URL"},
                    {"field": "mex:license", "label": "License"},
                    {"field": "mex:rights", "label": "Rights"},
                ],
            },
            "files": {
                "title": "Files",
                "icon": "distribution.svg",
                "properties": [
                    {"field": "mex:distribution", "label": "Distribution"},
                ],
            },
        },
    },
}

APP_RDM_DETAIL_SIDE_BAR_TEMPLATES = [
    "invenio_app_rdm/records/details/side_bar/metrics.html",
    "invenio_app_rdm/records/details/side_bar/versions.html",
    "invenio_app_rdm/records/details/side_bar/invenio_id.html",
    "invenio_app_rdm/records/details/side_bar/export.html",
]

APP_RDM_RECORD_EXPORTERS = {
    "json": {
        "name": _("JSON"),
        "serializer": ("flask_resources.serializers:JSONSerializer"),
        "params": {"options": {"indent": 2, "sort_keys": True}},
        "content-type": "application/json",
        "filename": "{id}.json",
    }
}

# List of entities available in mex model
ENTITIES = [
    "access-platform",
    "activity",
    "bibliographic-resource",
    "concept-scheme",
    "concept",
    "consent",
    "contact-point",
    "distribution",
    "organization",
    "organizational-unit",
    "person",
    "primary-source",
    "resource",
    "variable-group",
    "variable",
]

TITLE_FIELDS = [
    "mex:prefLabel",
    "mex:officialName",
    "mex:title",
    "mex:alternativeTitle",
    "mex:label",
    "mex:name",
    "mex:fullName",
    "mex:alternativeName",
    "mex:familyName",
    "mex:givenName",
    "mex:email",
]

DISCLAIMER = "All information is based on information from the original data-storing systems. No guarantee is given for the accuracy, completeness, or timeliness of this information."

FIELD_TYPES = get_field_types()
PREF_LABELS = get_pref_labels()
EXT_IDS = get_ext_ids(UI_SETTINGS)
FIELDS_LINKED_BACKWARDS = get_fields_linked_backwards(UI_SETTINGS)

CUSTOM_TYPES = field_types.CUSTOM_TYPES

# string to use when linked record is not found, must be something to not mix up with properties without value
NO_RECORD_STRING = "No record found"

# Celery Configuration for Bulk Indexing
# =======================================
# Increase task timeouts for heavy MEX record indexing with MexDumper

# Set task timeout to 30 minutes (1800 seconds) for bulk indexing operations
CELERY_TASK_TIME_LIMIT = 1800  # Hard limit - kills task after 30 minutes
CELERY_TASK_SOFT_TIME_LIMIT = 1500  # Soft limit - sends warning after 25 minutes

# Enable late acknowledgment to prevent lost tasks on timeout
CELERY_TASK_ACKS_LATE = True

# Reject tasks when worker is lost to prevent zombie tasks
CELERY_TASK_REJECT_ON_WORKER_LOST = True

# Indexer Configuration for MEX Records
# ====================================
# Override default bulk indexing settings to handle MEX record complexity

# Increase bulk request timeout from 10s to 10 minutes for heavy MEX operations
INDEXER_BULK_REQUEST_TIMEOUT = 600
