name: Release

run-name: release new version by @${{ github.actor }}

on:
  workflow_dispatch:

env:
  PIP_DISABLE_PIP_VERSION_CHECK: on
  PIP_NO_CLEAN: on
  PIP_NO_INPUT: on
  PIP_PREFER_BINARY: on
  PY_COLORS: "1"
  MEX_BOT_EMAIL: mex@rki.de
  MEX_BOT_USER: RKIMetadataExchange

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  containerize:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 1
          submodules: recursive
          persist-credentials: false

      - name: Login to container registry
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build, tag and push docker image
        env:
          IMAGE: ghcr.io/${{ github.repository }}
        run: |
          docker build . \
          --tag ${IMAGE}:latest \
          --tag ${IMAGE}:${{ github.sha }} \
          docker push --all-tags ${IMAGE}
